### ISSUE TITLE
Module not found: Error: Can't resolve 'use-sync-external-store/shim' after updating to 2.2.3

### ISSUE THREAD

**Issue by Synoo** [vercel/swr#2801] opened 2023-09-25 11:24 UTC
# Bug report

## Description / Observed Behavior

After updating to version 2.2.3 from 2.2.2, I get the following error: 

`ERROR in ../node_modules/swr/core/dist/index.mjs 3:0-68
Module not found: Error: Can't resolve 'use-sync-external-store/shim' in '/node_modules/swr/core/dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'use-sync-external-store/shim' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
`

## Additional Context

SWR version: 2.2.3
I saw the changelog of 2.2.3 and I think it has to do with:
Remove index.js suffix of use-sync-external-store/shim to support React Native by @malash in https://github.com/vercel/swr/pull/2767

**Comment by chhuang** [comment] 2023-09-25 11:28
May be related:

> unhandledRejection Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/chh/Documents/GitHub/my-app/node_modules/.pnpm/swr@2.2.3_react@18.2.0/node_modules/use-sync-external-store/shim' is not supported resolving ES modules imported from /Users/chh/Documents/GitHub/my-app/node_modules/.pnpm/swr@2.2.3_react@18.2.0/node_modules/swr/core/dist/index.mjs

> Did you mean to import use-sync-external-store@1.2.0_react@18.2.0/node_modules/use-sync-external-store/shim/index.js?

**Comment by vL1n** [comment] 2023-09-25 11:45
May be caused by this commit: https://github.com/vercel/swr/commit/a2bb5ae5df783c9b293c8ca1b4ef66a621d7d04e

**Comment by AndreasFaust** [comment] 2023-09-25 11:56
Manually appending `/index.js` to the line `import { useSyncExternalStore } from 'use-sync-external-store/shim';` in 
`node_modules/swr/core/dist/index.mjs` and `node_modules/swr/infinite/dist/index.mjs` seems to solve it temporarily.

**Comment by huozhi** [comment] 2023-09-25 12:38
Thanks for reporting! Reverted the chang from #2767 in #2802 , landed a new patch release `swr@2.2.4`. Please upgrade to the latest version 🙏

**Closed by huozhi** 2023-09-25 12:38 UTC
