### ISSUE TITLE
When revalidateOnMount = false, requests are never made

### ISSUE THREAD

**Issue by fermmm** [vercel/swr#943] opened 2021-01-31 20:37 UTC
I configured globally revalidateOnMount = false and no requests are made. Doing a request for the first time when there is no cache yet should not be considered re-validation since there is no "re.." in that action. At least a request should be made on first mount.

In my project I want my requests to only be sent when there is no cache, in other words: after the first call to useSwr() I want all the the following useSwr() to use the cache during all the life time of the application, or until I call mutate().
This is the correct behavior in applications when data is not required to be up to date. I can't figure out a global configuration where I can set this behavior, is it possible?  

This is my global configuration:

```
{
   refreshInterval: 0,
   errorRetryCount: 0,
   shouldRetryOnError: false,
   revalidateOnMount: false,
   revalidateOnFocus: false,
   revalidateOnReconnect: false,
   compare: (a, b) => a === b
}
```

I'm very surprised about having to search for this or open an issue because of this, maybe I'm doing something that nobody should do or something like that.  Also I can't figure out what is the use case for the current revalidateOnMount = false, who would ever need a useSwr() that does nothing?

**Comment by stnmonroe** [comment] 2021-02-09 23:25
I completely agree with this. A cache-first query would be ideal here, similar to Apollo. If data exists, good, otherwise query.

**Comment by underfisk** [comment] 2021-02-16 06:23
I also agree with this, i have to enforce revalidateOnMount in my project and what happens is that each time the parent re-renders that child, it will fetch the data even though nothing has changed for that.
Not sure if there's an alternative where we could set revalidateOnMount to false and it would just fetch the first line or if the key changes (which in my case it doesn't) but @fermmm is correct, there is no "re.." action to be done, it must be fetched the first time

**Comment by steven-mercatante** [comment] 2021-03-21 20:01
I'm running into this too. The headless CMS I'm using has a race condition, and I only want to revalidate manually via `mutate` calls.

I'm using this in a Next app, and could probably seed the `useSWR` call with initial data fetched from `getServerSideProps`, but that seems like many hoops to jump through for something that I think should be more straight-forward.

**Comment by xu3u4** [comment] 2021-03-30 10:30
I agree this is not an expected behavior for `revalidateOnMount`.
https://github.com/vercel/swr/blob/master/test/use-swr-integration.test.tsx#L48
Looks like the test also expects no fetching is made if `revalidateOnMount: false`.
Does anyone know why?

**Comment by fermmm** [comment] 2021-03-30 20:57
> I agree this is not an expected behavior for `revalidateOnMount`.
> https://github.com/vercel/swr/blob/master/test/use-swr-integration.test.tsx#L48
> Looks like the test also expects no fetching is made if `revalidateOnMount: false`.
> Does anyone know why?
> 
> By the way, I found a [solution](https://github.com/vercel/swr/issues/455#issuecomment-643504686) to only call the data if it is not in the cache. But then I can't think of a use case for `revalidateOnMount = false`.

I was using that workaround but has some limits, if you change the key it returns the same cache, to fix it you can add a useEffect to mutate() when the key is different but then you can't have a cache for each key, this translates into more requests to the server in that case

**Comment by tomevans18** [comment] 2021-04-09 20:47
This really threw me too, the docs don't allude to this setup either.

From the way the docs read, it would prevent a refetch on mount, effectively making the setup cached first.

Seems a bit of a pointless option as initialData also forces this behaviour too.

**Comment by joebartels** [comment] 2021-04-13 09:30
I agree with everyone in this thread. I was banging my head trying to get the same config that @fermmm is looking for.

It seems sensible to me that `revalidateOnMount: false` should do an initial fetch when cache is empty for the given key.

Or if there is a good reason for the current `revalidateOnMount` behavior then I may suggest a `singleFetchMode: true` config option that gives the behavior we're all looking for.

I would really really love  to see a solution to this before 1.0 🙏

**Comment by shuding** [comment] 2021-04-13 20:13
Yeah I've been thinking about this too, that's why I opened #992 specifically for this case: don't fetch if cached. 

I will try to add it in 1.0 soon, it would be great to hear more community feedback for it.

**Comment by TommySorensen** [comment] 2021-06-03 11:51
Isn't this fixed by setting the `dedupingInterval` to higher than `2000`which is the default value?

**Comment by efleurine** [comment] 2021-07-31 11:06
Ok so this is currently either a bug or the way it is supposed to work.

**Comment by hazae41** [comment] 2021-08-21 17:36
This workaround works fine

```typescript
const { data, error, mutate } = useSWR(key, fetcher, {
  revalidateOnFocus: false,
  revalidateOnMount: false,
  revalidateOnReconnect: false
})
useEffect(() => {
  if (data === undefined)
    mutate(undefined, true)
}, [key])
```

(if your fetcher doesn't return undefined)

**Comment by shuding** [comment] 2021-08-22 09:10
Hi all! With `swr@beta` you can use the new hook already:

```js
import useSWRImmutable from 'swr/immutable'
```

You can use it with "immutable" resources (those do not change over time). And the hook works just like `useSWR`, but only fetches if the data is not cached:

```js
useSWRImmutable(key, fetcher)
```

Let me know if there's any questions! Going to close this issue for now.

**Closed by shuding** 2021-08-22 09:10 UTC

**Comment by roker15** [comment] 2021-12-27 09:48
> revalidateIfStale



> Hi all! With `swr@beta` you can use the new hook already:
> 
> ```js
> import useSWRImmutable from 'swr/immutable'
> ```
> 
> You can use it with "immutable" resources (those do not change over time). And the hook works just like `useSWR`, but only fetches if the data is not cached:
> 
> ```js
> useSWRImmutable(key, fetcher)
> ```
> 
> Let me know if there's any questions! Going to close this issue for now.

So will it make network call if i refresh page? I want to make network call when  website is opened anytime after tab closed and not after that as long as tab is opened... is it possible.

**Comment by myxoh** [comment] 2022-10-06 18:52
`useSWRImmutable` - is not a full solution given it forces all the other properties to false.
In our case for example I wanted to keep the `revalidateOnFocus` and `refreshInterval` - it's just "on mount" is triggered when any component using that key is mounted, and that can happen more often than I need to revalidate the data...

From what I could test the behaviour achieved by what most people expect `revalidateOnMount: false` is achieved by `revalidateIfStale: false` (although it does have some other side effects).

**Comment by miragereth** [comment] 2023-04-12 19:41
> This workaround works fine
> 
> ```ts
> const { data, error, mutate } = useSWR(key, fetcher, {
>   revalidateOnFocus: false,
>   revalidateOnMount: false,
>   revalidateOnReconnect: false
> })
> useEffect(() => {
>   if (data === undefined)
>     mutate(undefined, true)
> }, [key])
> ```
> 
> (if your fetcher doesn't return undefined)

Does not work, as data will return undefined first render.

This behaviour is a malfunction, one wonders why the issue was closed without solution. It is not expected for the data to remain unloaded. This `revalidateOnMount = false` option ought to query on mount, and not revalidate on mount. Is not that to be expected?
It is not to be expected that `revalidateOnMount = true` launches frantic barrages of queries on mount, given that the data was recently served. Cache libraries are in use because queries are not necessarily free of charge.

**Comment by hyperparameters** [comment] 2023-04-16 06:29
I am also face the same issue, I don't want swr to revalidate all the data on mount. Its heavy api calls that run on certain page and it makes on sense to revalidate them unless manually specified.

I read all the comments and it absolutely make sense to cache 1st call and use the same cache on mount with the config `revalidateOnMount=false`

**Comment by miragereth** [comment] 2023-04-19 11:30
> I there any solution yet??

The used solution consisted in setting `revalidateOnMount=true`, and `dedupingInterval: 10000000`.
https://github.com/miragereth/mirage-shrine/blob/master/dapp/src/index.tsx

Queries require manual `mutate()` calls.

**Comment by ip10x** [comment] 2025-03-05 15:18
Here's what I did as a workaround which sets `revalidateOnMount` to `false` while also making the request initially if the cache is empty. In this example I'm getting the currently logged in user from the backend on the first call. Subsequent calls will use the SWR cache. 

The [solution](https://github.com/vercel/swr/issues/455#issuecomment-643504686) @xu3u4 mentioned doesn't completely work for me since I'm using SWR in a hook that is used many times throughout my app and the solution will initiate N requests instead of just one. To fix that I used a zustand store to synchronize the hooks. 

The Hook with SWR
```typescript
export function useLoggedInUser() {
  const { setIsLoggedInUserDataFetched } = useLoggedInUserStore()
  const isLoggedInUserDataFetched = useLoggedInUserStore((state) => state.isLoggedInUserDataFetched)

  const { data, isLoading, error, mutate } = useSWR(
    '/api/get-logged-in-user',
    theFetcher,
    {
      revalidateOnFocus: false,
      revalidateOnMount: false,
    }
  );

  useEffect(() => {
    if (!useLoggedInUserStore.getState().isLoggedInUserDataFetched && !data) {
      setIsLoggedInUserDataFetched()
      mutate()
    }
  }, [isLoggedInUserDataFetched, data, mutate]);
}
```
The zustand Store
```typescript
import { create } from 'zustand';

interface StoreState {
  isLoggedInUserDataFetched: boolean
  setIsLoggedInUserDataFetched: () => void;
}

export const useLoggedInUserStore = create<StoreState>((set) => ({
  isLoggedInUserDataFetched: false,
  setIsLoggedInUserDataFetched: () => {
    set({ isLoggedInUserDataFetched: true })
  },
}));
```

**Comment by linzeguang** [comment] 2025-03-21 08:47
Why was the issue closed without being resolved?
I want the request to be triggered on the initial render even when revalidateOnMount: false.
Right now, when revalidateOnMount: true, it triggers the request twice—once during initialization and once on mount.
