### ISSUE TITLE
Help needed: Error: Invalid hook call

### ISSUE THREAD

**Issue by gnoyixiang** [vercel/swr#431] opened 2020-06-06 09:51 UTC
Hello, I was just trying to use swr with a next.js project but encountered the "Invalid hook call" error. I also tried to clone the "basic" example provided in the repository, but ran into the same error too. Need some advice please. Thanks in advance!

![image](https://user-images.githubusercontent.com/30717323/83941471-21eeba00-a81e-11ea-9297-27c2beeaaca9.png)

**Comment by shuding** [comment] 2020-06-06 13:16
Do you mind sharing your code (and `package.json`)? Or you can create an reproduction on https://codesandbox.io so we can help take a look.

**Comment by robertgrzonka** [comment] 2020-06-07 11:33
Well, the answer is already contained in your question and provided as a link: https://reactjs.org/warnings/invalid-hook-call-warning.html 

> From Reacts docs we can also read:
<img width="897" alt="Zrzut ekranu 2020-06-7 o 13 25 49" src="https://user-images.githubusercontent.com/35585466/83967515-85cabe80-a8c2-11ea-91e2-fa9910527dc3.png">

Please change `export default () => { ... }` to function component like:
```javascript
const NextComponent = (props) => {
   const { data } = useSWR('/api/data', fetch)

    return (
        ...
    )
```

**Comment by illuminist** [comment] 2020-06-08 07:04
@robertgrzonka It already is a functional component. As long as you create a function to return any kind of react node, it's a function component.

The difference is that functional component with hook is required to be used in conjunction  with `React.createElement` (translated from JSX tag), and cannot be called by itself as regular function.

**Comment by robertgrzonka** [comment] 2020-06-08 07:18
Thank you for clarifying, I shouldn’t use shortcut 😅

**Comment by shuding** [comment] 2020-06-08 08:22
Thanks @illuminist @robertgrzonka, the basic example works for me as well. Closing this issue until we have a reproduction.

**Closed by shuding** 2020-06-08 08:22 UTC
Labels: help wanted

**Comment by jackhkmatthews** [comment] 2021-12-26 19:11
Hi @gnoyixiang,

I also had this issue. Turned out I'd installed SWR into the root of my mono-repo instead of my NextJS app's subdirectory.

**Comment by rujmah** [comment] 2022-01-31 22:35
@jackhkmatthews 🤦 thank you so much! I thought I was going crazy.

**Comment by MinyoungRsup2** [comment] 2023-06-06 16:41
@jackhkmatthews 

THE EXACT THING HAPPENED TO ME AND I THOUGHT I WAS GOING INSANE
