### ISSUE TITLE
Fetcher not triggered after dependancy array change if initialData is present

### ISSUE THREAD

**Issue by Swearengen** [vercel/swr#804] opened 2020-12-11 15:36 UTC
# Bug report

## Description / Observed Behavior

I am using SWRInfinite along with some filtering using query params.  If I click to load more and call setSize everything works but if I try to read query param (?page=2) and react to that param change, the fetcher is not called, even though the page is inside dependency array. 
Observed behavior is happening only if initialData option is used

## Expected Behavior

I would expect that the fetcher is called every time some value inside the dependency array is changed.

The hotfix for that could be to remove initialData option if it's not first render

## Repro Steps / Code Example

1. Go to infinite load page
2. click "change query param" button

[CodeSandbox](https://codesandbox.io/s/with-initial-data-wlgp7)

## Additional Context

SWR version: 0.3.6

**Comment by Kerumen** [comment] 2020-12-28 14:52
Duplicate of https://github.com/vercel/swr/issues/284

**Closed** 2021-01-04 08:49 UTC
