### ISSUE TITLE
Property 'clear' does not exist on type 'Cache<any>'

### ISSUE THREAD

**Issue by Kamahl19** [vercel/swr#1634] opened 2021-11-12 18:56 UTC
# Bug report

## Description / Observed Behavior

After doing 

```
  const { cache } = useSWRConfig();
  cache.clear();
```

I get `Property 'clear' does not exist on type 'Cache<any>'`

## Repro Steps / Code Example

https://codesandbox.io/s/create-react-app-typescript-forked-w38yc?file=/src/index.tsx

## Additional Context

SWR 1.0.1

**Comment by shuding** [comment] 2021-11-12 21:18
Closing as duplicate of #1502.

**Closed by shuding** 2021-11-12 21:18 UTC
