### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by niamleeson** [vercel/swr#522] opened 2020-07-14 19:20 UTC
# Bug report

## Description / Observed Behavior

When building the app with NextJS in Jenkins, the build fails with the following error message:

```
ReferenceError: navigator is not defined
    at Object.641 (/app/node_modules/swr/dist/index.js:1:11816)
    at __webpack_require__ (/app/node_modules/swr/dist/index.js:1:154)
    at Object.516 (/app/node_modules/swr/dist/index.js:1:3661)
    at __webpack_require__ (/app/node_modules/swr/dist/index.js:1:154)
    at Object.325 (/app/node_modules/swr/dist/index.js:1:1394)
    at __webpack_require__ (/app/node_modules/swr/dist/index.js:1:154)
    at startup (/app/node_modules/swr/dist/index.js:1:291)
    at module.exports.202 (/app/node_modules/swr/dist/index.js:1:323)
    at Object.<anonymous> (/app/node_modules/swr/dist/index.js:1:333)
    at Module._compile (internal/modules/cjs/loader.js:959:30) {
```

## Expected Behavior

The build should succeed

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

NextJS 9.1.5
SWR 0.2.3

**Comment by huozhi** [comment] 2020-07-15 13:26
@niamleeson how do you run the tests and what are the testing tools you're using? from the log I saw the module resolved the cjs build of swr so I think it's testing running inside Node.js instead of browser runtime.

did you try to use jsdom to polyfill browser runtime stuff like (window, navigator, etc.)? or probably try jest with jsdom env enabled to run the tests?

**Comment by niamleeson** [comment] 2020-08-11 18:39
This was happening during development as well. I had to do the following in `_app.jsx`

```
import App, { Container } from 'next/app';
if (typeof global.navigator === 'undefined') global.navigator = {};
// const navigator = {};

class MyApp extends App {
    // ...
}
```

**Comment by huozhi** [comment] 2020-08-12 09:24
swr will access `window.navigator` in browser runtime only rather than the node.js or any server side. could you provide minial reproducible sample or code snippet for this issue? will be great helpful for us to identify the root cause.

**Comment by niamleeson** [comment] 2020-08-31 17:44
I tried really hard to get a reproducible code, but it looked like it has something to do with the compilation process. I even got to a place where I commented out one component that didn't use `useSWR` and the next build would finish successfully. Then I would uncomment the component back and the build would fail with the navigator message.

However, I did manage to permanently fix it by using this module and specifying `swr` in it: https://github.com/wellcometrust/next-plugin-transpile-modules

**Comment by MrNghia123** [comment] 2020-09-04 06:06
I upgraded swr from 0.3.1 to 0.3.2 and it fixed the problem.

**Comment by MrNghia123** [comment] 2020-09-04 06:17
The problem seems to be still around in another form. Version 0.3.2 let me build successfully both locally and on Vercel but going to the page presents this runtime problem (from vercel log -f command).

2020-09-04T06:14:02.002Z      ef446b94-a2e0-4cae-9f81-5ce058068f0c    INFO    info  - Loaded env from .env.production
                          2020-09-04T06:14:03.486Z      ef446b94-a2e0-4cae-9f81-5ce058068f0c    ERROR   Unhandled error during request: ReferenceError: navigator is not defined
                              at Object.641 (/var/task/node_modules/swr/dist/index.js:1:11265)
                              at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)
                              at Object.516 (/var/task/node_modules/swr/dist/index.js:1:3693)
                              at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)
                              at Object.325 (/var/task/node_modules/swr/dist/index.js:1:1420)
                              at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)
                              at startup (/var/task/node_modules/swr/dist/index.js:1:291)
                              at module.exports.202 (/var/task/node_modules/swr/dist/index.js:1:323)
                              at Object.<anonymous> (/var/task/node_modules/swr/dist/index.js:1:333)
                              at Module._compile (internal/modules/cjs/loader.js:1138:30)
                          2020-09-04T06:14:03.495Z      ef446b94-a2e0-4cae-9f81-5ce058068f0c    ERROR   Uncaught Exception      {"errorType":"ReferenceError","errorMessage":"navigator is not defined","stack":["ReferenceError: navigator is not defined","    at Object.641 (/var/task/node_modules/swr/dist/index.js:1:11265)","    at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)","    at Object.516 (/var/task/node_modules/swr/dist/index.js:1:3693)","    at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)","    at Object.325 (/var/task/node_modules/swr/dist/index.js:1:1420)","    at __webpack_require__ (/var/task/node_modules/swr/dist/index.js:1:154)","    at startup (/var/task/node_modules/swr/dist/index.js:1:291)","    at module.exports.202 (/var/task/node_modules/swr/dist/index.js:1:323)","    at Object.<anonymous> (/var/task/node_modules/swr/dist/index.js:1:333)","    at Module._compile (internal/modules/cjs/loader.js:1138:30)"]}
                          Duration: 1613.03 ms  Billed Duration: 1700 ms        Memory Size: 1024 MB    Max Memory Used: 59 MB
                          Unknown application error occurred

**Comment by lildata** [comment] 2021-01-08 21:06
I do get the same `ReferenceError: navigator is not defined` when trying to use SWR in an Ink app (https://github.com/vadimdemedes/ink)
(The SWR requests do succeed tho)

```
ReferenceError: navigator is not defined
    at Object.isOnline (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:1636)
    at Object.<anonymous> (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:10779)
    at step (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:3829)
    at Object.next (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:3114)
    at /home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:2799
    at new Promise (<anonymous>)
    at n (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:2547)
    at Timeout.r [as _onTimeout] (/home/me/dev/git/my-ink-cli-2/node_modules/swr/dist/index.js:1:10575)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

## Additional Context
nodejs: 14.15.1
swr: 0.4.0
react: 17.0.1
ink: 3.0.8
typescript: 4.1.3

**Comment by huozhi** [comment] 2021-01-09 03:16
@lildata currently swr can only works very smoothly in browser runtime only (the time when I wrote this reply). the short unofficial work around could be:

```js
useSWR(key, fetcher, {
  isOnline() { /* online detector for ink runtime */ },
  isDocumentVisible() { /* online detector for ink runtime */ },
})
```

making swr become more flexible for different runtime is still in progress :)

**Comment by lildata** [comment] 2021-01-09 10:37
@huozhi Many thanks & my bad I just assumed node was supported...

**Comment by pacocoursey** [comment] 2021-01-13 06:39
Closing as it's been made clear that SWR only supports a browser environment, for now, and better error handling has been added!

**Closed by pacocoursey** 2021-01-13 06:39 UTC

**Comment by pke** [comment] 2021-11-13 03:19
hmmm I don't know. My jest tests ran just fine with react-native 0.63.3 and now started to fail with 0.66.3
All of the sudden all swr related tests fail.
