### ISSUE TITLE
useSWRInfinite always make 2 calls for api (page 1 and page n)

### ISSUE THREAD

**Issue by Ilya-Valasiuk** [vercel/swr#1706] opened 2021-12-13 18:49 UTC
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

Always 2 requests sends to API:
1) with page number 1
2) with page number N

## Expected Behavior
1 request should be created with page N

How did you expect SWR to behave here?

## Repro Steps / Code Example

Install https://github.com/vercel/swr/tree/main/examples/infinite-scroll

Take a look in Network tab
![image](https://user-images.githubusercontent.com/4801973/145870337-7b7fdcef-ac56-4d01-bd30-a3df9e60bdf1.png)

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version. 

It works as expected for very old version :) Example - https://swr.vercel.app/examples/infinite-loading

**Comment by shuding** [comment] 2021-12-13 19:28
Duplicate of #1638, as I explained there:

> Since SWR 1.1.0, there is a new option `revalidateFirstPage` that you can use to turn this off. Related docs: https://github.com/vercel/swr/releases/tag/1.1.0
>
> If you are interested, here are the full discussions of why we built this feature in the first place: https://github.com/vercel/swr/issues/1401#issuecomment-907764278, and why we now provide this new option to customize it.
> 
> Let me know if it helps you!

**Closed by shuding** 2021-12-13 19:28 UTC

**Comment by Ilya-Valasiuk** [comment] 2021-12-13 19:39
@shuding thank you, got it
