### ISSUE TITLE
setSize on useSWRInfinite when page index is null output object as data instead of undefined

### ISSUE THREAD

**Issue by mhsattarian** [vercel/swr#1286] opened 2021-07-11 16:24 UTC
# Bug report

## Description / Observed Behavior

When page index (first parameter of `useSWRInfinite`) is `null` and setSize method is called, data instead of being `undefined` (as expected) becomes an object as below:

```
{
	data: undefined,
    "force": false
}
```

## Expected Behavior

It should output `undefined` as data.

## Repro Steps / Code Example

use the [swr-infinite CodeSandbox](https://codesandbox.io/s/swr-infinite-z6r0r) from the docs and change version to `0.5.6`.
or use [this CodeSandbox](https://codesandbox.io/s/swr-infinite-forked-codtb?file=/src/App.js).

## Additional Context

this was ok in version `0.3.0` as I tested in [swr-infinite CodeSandbox](https://codesandbox.io/s/swr-infinite-z6r0r), but it's not now in `0.5.6`.

I hadn't investigated the problem, but I think there might be an issue with this line:

https://github.com/vercel/swr/blob/c677d042c1307e00c641a2fbe8b559a1413670b5/infinite/index.ts#L110

I guess it should be like this?:

```
const { data: pageData, force } = cache.get(pageKey)
```

**Comment by shuding** [comment] 2021-07-18 11:29
This bug should have been fixed in the latest beta, I cannot reproduce it here: https://codesandbox.io/s/swr-infinite-forked-mx7wc.

**Closed by shuding** 2021-07-18 11:29 UTC
