### ISSUE TITLE
Issue using swr in webpack 5

### ISSUE THREAD

**Issue by transitive-bullshit** [vercel/swr#1112] opened 2021-04-07 02:52 UTC
# Bug report

## Description / Observed Behavior

Using Next.js `10.1.3` with webpack 5 enabled via: `future: { webpack5: true }` added to `next.config.js`, I get the following error when trying to use `swr`:

```
TypeError: swr__WEBPACK_IMPORTED_MODULE_2__ is not a function
    at Object.eval [as render] (webpack-internal:///../packages/react-static-tweets/build/esm/tweet.js:20:20)
    at ReactDOMServerRenderer.render (/Users/fisctrav/dev/react-static-tweets/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (/Users/fisctrav/dev/react-static-tweets/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/fisctrav/dev/react-static-tweets/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///../node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/render.js:54:1145)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/next-server.js:138:522)
    at async DevServer.renderToHTML (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/server/next-dev-server.js:35:578)
    at async DevServer.render (/Users/fisctrav/dev/react-static-tweets/node_modules/next/dist/next-server/server/next-server.js:75:236)
```

Here is the original TS code that is causing this issue: https://github.com/transitive-bullshit/react-static-tweets/blob/master/packages/react-static-tweets/src/tweet.tsx#L21

## Expected Behavior

If I disable webpack 5 and switch back to Next.js using webpack 4, the error goes away and everything works as expected. Webpack compiles the package and swr correctly, and my Next.js app works without issues.

## Repro Steps / Code Example

This behavior is reproducible if you try running the `example` project contained in this repo: https://github.com/transitive-bullshit/react-static-tweets

## Additional Context

```json
{
"swr": "^0.5.5",
"next": "^10.1.3",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-static-tweets": "^0.5.1",
"static-tweets": "^0.5.1"
}
```

This may have to do with how [react-static-tweets](https://github.com/transitive-bullshit/react-static-tweets) is transpiling from TS to ESM (which requires `swr` under the hood` [here](https://github.com/transitive-bullshit/react-static-tweets/blob/master/packages/react-static-tweets/src/tweet.tsx#L21)), but honestly I've been trying to debug this for a few hours without much luck.

Any help's appreciated && thanks 🙏

**Comment by huozhi** [comment] 2021-04-07 03:29
@transitive-bullshit can you provide a static and minimal repro (maybe a codesandbox) for this issue? would be easier to diagnose the root cause. I tried cloning / running the example locally, get the totally different error message. I see you are still pushing to the codebases.

**Comment by shuding** [comment] 2021-04-07 10:53
Hi @transitive-bullshit could you please try `swr@beta`? We are using Webpack 5 and SWR (tested both latest and beta) in production and they work fine. We will investigate the error you shared.

**Comment by shuding** [comment] 2021-04-13 10:41
Closing this due to https://github.com/transitive-bullshit/react-static-tweets/issues/23#issuecomment-818619457.

**Closed by shuding** 2021-04-13 10:41 UTC
Labels: bug

**Comment by Mandy9943** [comment] 2023-11-01 14:10
Is sho wired I have using in my project many month and now in a particular react component just dont work with this error... in the rest of the app still working but not working in just 1 place with the error in the image
![image](https://github.com/vercel/swr/assets/74042888/b0648864-a53d-44f3-9cb8-5f705e472bc8)

the implementation is the following 

```
import axiosDapfy from "@/services/rest/dapfy-api";
import useSWR from "swr";

const fetcher = async (url) => {
  const res = await axiosDapfy.get(url);

  return res.data;
};

  const { data, error, isLoading } = useSWR(
    "/api/purchases?address=" + "address",
    fetcher
  );
  
  

```

**Comment by Mandy9943** [comment] 2023-11-01 14:18
Sorry problem fixed! Forget to the "use client", I think I should get a warning for that

**Comment by benlhachemi** [comment] 2023-11-24 08:38
> Sorry problem fixed! Forget to the "use client", I think I should get a warning for that

thanks, I spent 30 min looking for a solution, and all what I needed is 'use client' lol

**Comment by bayzed5** [comment] 2024-03-16 13:28
use client - lol , buts its work fine 😎😎
