### ISSUE TITLE
isValidating from useSWRInfinite is an empty string after mutate()

### ISSUE THREAD

**Issue by maciej-lepb** [vercel/swr#1195] opened 2021-06-02 14:29 UTC
# Bug report

## Description / Observed Behavior

`isValidating` from `useSWRInfinite` is an empty string (`""`) after `mutate()` is called for an errored request.

The sequence is:
1. useSWRInfinite...
2. `isValidating` is true (correct)
3. request fails with 500, `isValidating` is false (correct)
4. `mutate()` is called (the same is with `mutate(undefined, false)` and `mutate(undefined, true)`
5. `isValidating` becomes an empty string

## Expected Behavior

`isValidating` should always be a boolean.

## Repro Steps / Code Example

```typescript
const { data, error, size, setSize, isValidating, mutate } = useSWRInfinite(
  getKeyWrapped,
  fetcher,
  swrOptions,
);

console.log('isValidating:', typeof isValidating, isValidating);
// ...
// mutate()
// ...
console.log('isValidating:', typeof isValidating, isValidating);
```

For a request that fails with status code 500, I am getting the following output:
`isValidating: boolean true`
`isValidating: string  `

## Additional Context

SWR version: 0.5.6

**Comment by koba04** [comment] 2021-06-03 13:27
@maciej-lepb Could you provide a [CodeSandbox](https://codesandbox.io) project to  re-produce this?

**Comment by Janpot** [comment] 2021-07-27 08:18
@koba04 Seeing this as well, only happens on the first time that `useSWR` key switches from `null` to a string. Reproduction: https://codesandbox.io/s/fragrant-snow-pih92?file=/pages/index.js

**Comment by shuding** [comment] 2021-07-27 12:40
It seems to be fixed with `swr@beta`: https://codesandbox.io/s/affectionate-margulis-52s8n.

**Closed** 2021-07-29 13:10 UTC
