### ISSUE TITLE
Prevent useSwr from fetching until mutate() is called 

### ISSUE THREAD

**Issue by dav1d992** [vercel/swr#1692] opened 2021-12-06 09:39 UTC
I have a React application which uses SWR + Axios for data fetching ([https://swr.vercel.app/docs/data-fetching][1]). The issue is that my custom hook which uses `useSwr` is fetching all data initially whenever the hook is initialized. My goal is to fetch only when I call `mutate`. Currently the initial fetch is happening even without calling `mutate`. 

It seems it doesn't solve my issue by adding the options: 
```
    {
      revalidateOnFocus: false,    
      revalidateOnMount: false,
      revalidateOnReconnect: false,
      refreshWhenOffline: false,
      refreshWhenHidden: false,
      refreshInterval: 0,
    }
```
**Any suggestion on how to achieve my goal here?** 

My application is wrapped in SWRConfig: 
```
    <SWRConfig
      value={{
        fetcher,
      }}
    >
      <App/>
    </SWRConfig>
```

The fetcher is described as so: 
```
const dataFetch = (url) => axios.get(url).then((res) => res.data);

function fetcher(...urls: string[]) {
  if (urls.length > 1) {
    return Promise.all(urls.map(dataFetch));
  }
  return dataFetch(urls);
}

```

My custom hook using `useSwr` 
```
import useSWR, { useSWRConfig } from "swr";

export function useCars(registrationPlates: number[]): ICars {
  const { mutate } = useSWRConfig();
  const { data: carData} = useSWR<Car[]>(
    carsToFetchUrls(registrationPlates),  // returns string array with urls to fetch
    {
      revalidateOnFocus: false,    
      revalidateOnMount: false,
      revalidateOnReconnect: false,
      refreshWhenOffline: false,
      refreshWhenHidden: false,
      refreshInterval: 0,
    }
  );

  const getCar = (
    carRegistrationPlate: number,
  ): Car => {
    console.log(carData) // carData contains data from fetch even before calling mutate()

    void mutate();
    
    ...
}
```

Usage: (this will be located in some component that wants to use the `useCars` hook) 
```
const { getCar } = useCars(carsRegistrationPlates);
```

  [1]: https://swr.vercel.app/docs/data-fetching

SWR version. 
"swr": "^1.0.0",

**Comment by rkoleci** [comment] 2021-12-06 13:07
Can you assign this to me ?

**Comment by shuding** [comment] 2021-12-23 19:42
Closing this as we do have test for `revalidateOnMount` and it's working fine: https://github.com/vercel/swr/blob/a26728424b20cdba4b4c05ebd66c324f3aec6660/test/use-swr-integration.test.tsx#L58-L73

If you have `revalidateOnMount: false` and this is still happening, could you create a reproduction with https://codesandbox.io/s/swr-basic-p7dg6? I can't reproduce it personally.

> Currently the initial fetch is happening even without calling mutate.

**Closed by shuding** 2021-12-23 19:42 UTC
Labels: bug
