### ISSUE TITLE
Status indicator

### ISSUE THREAD

**Issue by conradreuter** [vercel/swr#141] opened 2019-11-20 18:07 UTC
I think the result should have a field indicating the status of the query. It could be a simple boolean flag `loading` or a more sophisticated `status` enum (to indicate revalidation, etc.).

Checking `data` for truthiness does not cut it if you consider that the data returned from the fetcher could in theory be `null` (or even `undefined`).

**Comment by quietshu** [comment] 2019-11-21 01:43
There’s the `isValidating` value returned by `useSWR`, you can simply use it as the loading indicator.

**Comment by aequasi** [comment] 2019-11-21 04:35
You can’t reliably use that to check if dat has not been set yet though

**Comment by pkhodaveissi** [comment] 2020-07-11 08:00
That'd be great, react-async package has this great enum:

```export enum StatusTypes {
  initial = "initial",
  pending = "pending",
  fulfilled = "fulfilled",
  rejected = "rejected",
}```

**Comment by ivan-kleshnin** [comment] 2021-02-12 12:31
> Checking data for truthiness does not cut it if you consider that the data returned from the fetcher could in theory be null (or even undefined).

Much worse, `empty data = loading` assumption works only for the first request. 
For all consequent requests (refetches) from the same `useSWR` data will not be empty.

**Comment by darrenjennings** [comment] 2021-02-28 19:30
I have thought about adding this feature to `swrv` (vue implementation) because right now we use a user-land hook to determine the enum, which uses data/error/isValidating. It is kind of annoying that it's not built-in to the main return value.

https://docs-swrv.netlify.app/features.html#useswrvstate

```ts
const STATES = {
  PENDING: 'PENDING', // no data, initial loading
  VALIDATING: 'VALIDATING', // there is data, but validation is occurring
  SUCCESS: 'SUCCESS', // data exists and no in-flight requests
  ERROR: 'ERROR', // error, no data
  STALE_IF_ERROR: 'STALE_IF_ERROR', // error exists, but there is still some cached data we can show
}
```

**Comment by shuding** [comment] 2021-03-06 22:32
Thanks for sharing @darrenjennings! I'll also add my 2 cents.

I love the idea, but enum is a bit annoying to me. What do you think about this proposal:

```js
const { data, error, state } = useSWR(...)

state.pending // => true
state.success // => false
state.error // => false
```

The good thing is that users don't need to import all the enums, and the editor will autocomplete. 

---

The only concern for this status indicator idea is, since we are building these "high-level" states, their names have to be very clear and have to be **complete**.

**Complete** means that we have a group of 3 base values (data, error, isValidating) and all of them have 2 states, the derived states will be 2^3 = 8 different possibilities. It grows exponentially:

- (data = 0, error = 0, isValidating = 0): idle
- (data = 0, error = 0, isValidating = 1): pending
- (data = 1, error = 0, isValidating = 0): success
- (data = 0, error = 1, isValidating = 0): error
- (data = 0, error = 1, isValidating = 1): retrying
- (data = 1, error = 0, isValidating = 1): revalidating
- (data = 1, error = 1, isValidating = 0): error_stale
- (data = 1, error = 1, isValidating = 1): retrying_stale

These are a lot and I believe there is at least one use case for each state. So I preferred to leave it to the users to determine which states their app needs. But after all I can see the benefit of directly returning the ready-to-use app state to the user.

**Comment by darrenjennings** [comment] 2021-03-07 19:50
@shuding I like the naming of all 8 states! Even though it seems like it could grow exponentially, it does limit the guesswork on how many states your swr-dependent ui can devolve into*. Though we had some discussion [here](https://github.com/vercel/swr/discussions/440#discussioncomment-24095) around the ambiguity of the state names e.g. "what is 'error'?". I think it can mostly be explained to say a swr state `error` is "fetcher threw". If you don't want to throw (e.g. 404 == user is logged out), then you can catch in your fetcher.

> I love the idea, but enum is a bit annoying to me. The good thing is that users don't need to import all the enums, and the editor will autocomplete.

It would be my preference to define them as string literals so that you can do simple equality checks that can be used with useReducer or switch statements without having to check multiple `state.*` flags. This gives you editor autocomplete as well. It is more of a state machine way to do it.

```ts
type swrState =
| 'idle'
| 'pending'
| 'success'
| 'error'
| 'retrying'
| 'revalidating'
| 'error_stale'
| 'retrying_stale'
```

\* and maybe it is overblown to think there is another property that would be introduced, maybe cancelled? I never cancel requests so open to if you think there would be a new state that would give it 16 states.

**Comment by sebastienlabine** [comment] 2021-03-22 22:05
Please implement this. At least for inital data fetching. It's so annoying to work with !data & !error on a component level. The simplest use of the SWR result require to handle undefined cases all the time.

For example, I can't do this without handling the data= undefined case 
```
const { data} = useSWR('/insights', url => axios.get<number[]>("http://localhost:61197/v1/insights).then(res => res.data))

var referingSitesColors = useMemo(() => {
        return chroma.scale(["#fa4d56", "#fff1f1"]).colors(data.length)
    }, [data])
```

and I can't use this case because I don't have access to the loading state.

```
const { data = []} = useSWR('/insights', url => axios.get<number[]>("http://localhost:61197/v1/insights).then(res => res.data))

var referingSitesColors = useMemo(() => {
        return chroma.scale(["#fa4d56", "#fff1f1"]).colors(data.length)
    }, [data])
```

**Comment by huozhi** [comment] 2021-06-28 18:43
For various use cases, user can customize their own status indicator logic on top of SWR. Close it as it's something as designed in current phase.

**Closed by huozhi** 2021-06-28 18:43 UTC
