### ISSUE TITLE
Problems with mutate and input[type="datetime-local"]

### ISSUE THREAD

**Issue by dudusotero** [vercel/swr#527] opened 2020-07-15 21:31 UTC
Hello everyone! I'm here to show a quick problem I have at this moment.

Why when I submit a form and do a mutate with the new form values, all input with type "datetime-local" changes to another value?

I made a quick example of my problem, so everyone can check without do any code: [link here](https://stackblitz.com/edit/react-kpf1yh)

Gif with the occurring problem:
![ezgif-3-b37182d6428e](https://user-images.githubusercontent.com/7073199/87592555-752b1680-c6c0-11ea-9871-20302026430d.gif)

**Comment by sergiodxa** [comment] 2020-07-16 04:01
This is a duplicate of #526, let's continue the discussion there 😉

**Comment by shuding** [comment] 2020-09-20 17:32
This is the expected behavior of SWR, the stale data is rendered, and an updated and random new date returned (which replaced the existing one). 

I believe that if you don't use the mock up API, the dates will be consistent and it will be fine.

**Closed by shuding** 2020-09-20 17:32 UTC
