### ISSUE TITLE
[Bug] 1.2.0 breaks Nextjs/Yarn 3 PnP/Zero Install

### ISSUE THREAD

**Issue by dgattey** [vercel/swr#1822] opened 2022-01-29 04:01 UTC
# Bug report

Hate to open this! I love `swr` and it usually works great. But I just did an upgrade and it broke my build 😢 [Repo branch that repros it](https://github.com/dgattey/dg/tree/broken/swr).

I upgraded from 1.1.2 to 1.2.0 and my NextJS/Yarn 3 project with PnP and zero install active broke. `yarn next dev` or `yarn next build` errors because it can't find the `swr` module at all as this shows:
![image](https://user-images.githubusercontent.com/982182/151646094-af7ccbc4-bf2c-493f-97e5-74ee4009de4c.png)

I think I narrowed it down to [this commit](https://github.com/vercel/swr/commit/c6bf094ce3c6d3fc33ecdc693600fbf6175ada8b). It changes the exports swr provides and landed between beta 0 and beta 1 of 1.2.0. Consequently, installing version 1.2.0-beta.0 works perfectly, but version 1.2.0-beta.1 breaks it (albeit with a slightly different error, but still one about not being able to resolve swr). 

## Description / Observed Behavior

Getting this error with swr 1.2.0:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'swr' imported from /Users/dgattey/checkouts/dg/.next/server/pages/index.js
```

## Expected Behavior

For SWR to be able to be resolved into a real package location.

## Repro Steps / Code Example

Check out the [broken/swr branch of this repo](https://github.com/dgattey/dg/tree/broken/swr). Happy to give access if useful/explain anything.

**Comment by shuding** [comment] 2022-01-29 10:39
Oh no! I’m taking a look, thanks for opening this!

**Comment by shuding** [comment] 2022-01-29 11:57
OK did some testing with npm, pnpm, Yarn 1 and all seem to be good. This feels like an issue with Yarn PnP (I can reproduce with your repository).

**Comment by huozhi** [comment] 2022-01-29 15:56
@dgattey I release a patch for fixing this yarn pnp issue, could you try `swr@1.2.1-experimental.0` to see if it works? If it's good we'll get it released into stable patch asap

**Comment by dgattey** [comment] 2022-01-30 09:48
Well, fixes the serverside error in the console when running `yarn dev`, but now I'm getting an error about the `.cjs` file in the browser that I wasn't before. Also getting the same cjs error on `yarn build`. The branch I linked above has the upgrade changes.
```
Error: Cannot find package 'swr' imported from /Users/dgattey/checkouts/dg/.next/server/pages/_error.js
Did you mean to import swr-virtual-c677ae8285/0/cache/swr-npm-1.2.1-experimental.0-925e0e326c-4df3d54390.zip/node_modules/swr/dist/index.cjs?
```

**Comment by huozhi** [comment] 2022-01-31 14:51
@dgattey I tested `swr@1.2.0` it works with yarn pnp + create-next-app.
I still couldn't run your project, could you provide a minimal reproduction that's easy to test?

![image](https://user-images.githubusercontent.com/4800338/151815129-c7228127-3865-4498-b26c-c757ef7ed0a4.png)

**Comment by dgattey** [comment] 2022-01-31 19:37
@huozhi Oh, @shuding said they could reproduce with my repo. I don't have time this week to try to repro in a different setup. Did you run yarn with yarn 3 installed and then try yarn build? All off the dependencies should be there minus some keys

**Comment by dgattey** [comment] 2022-02-03 08:42
@huozhi @shuding Got a minimal repro going on at https://github.com/dgattey/dg/tree/broken/swr - I deleted everything that wasn't needed to cause it to error. App is my configs + one single page that tries to `useSWR` and fails. Nothing crazy. `yarn dev` or `yarn build` both show the error here.

This is upgraded to 1.2.1

**Comment by huozhi** [comment] 2022-02-05 18:44
Looks like it's a yarn issue, check this [next.js issue comment](https://github.com/vercel/next.js/issues/30873#issuecomment-961246661)

I followed the comment [here from this yarn issue](https://github.com/yarnpkg/berry/issues/3687#issuecomment-957240140) and then run `yarn install`.

Clean the `.next` folder, run `yarn dev`, it works.

**Closed by huozhi** 2022-02-05 18:44 UTC
Labels: bug
